services:
  pylatam:
    image: "pylatam"
    container_name: "pylatam"
    env_file: pylatam.env
    build: ..
    networks:
      - apps

    labels:
      - traefik.http.routers.pylatam.rule=Host(`demo.pylatam.org`)
      - traefik.http.routers.pylatam.tls=true
      - traefik.http.routers.pylatam.tls.certresolver=le
      - traefik.http.routers.pylatam.entrypoints=websecure
      - traefik.port=80
      - traefik.enable=true

  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      #- "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.le.acme.email=postmaster@pylatam.org"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - apps

networks:
  apps:
    driver: bridge


volumes:
  letsencrypt:

